
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry entry1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry entry2;

	private global::Gtk.Button add;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Entry sub_ent_one;

	private global::Gtk.Label label2;

	private global::Gtk.Entry sub_ent_two;

	private global::Gtk.Button subtract;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Entry mult_ent_one;

	private global::Gtk.Label label3;

	private global::Gtk.Entry mult_ent_two;

	private global::Gtk.Button multiply;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Entry div_ent_one;

	private global::Gtk.Label label5;

	private global::Gtk.Entry div_ent_two;

	private global::Gtk.Button divide;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.hbox1.Add(this.entry1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry1]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("+");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.hbox1.Add(this.entry2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry2]));
		w3.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.add = new global::Gtk.Button();
		this.add.CanFocus = true;
		this.add.Name = "add";
		this.add.UseUnderline = true;
		this.add.Label = global::Mono.Unix.Catalog.GetString("add");
		this.hbox1.Add(this.add);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.add]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.sub_ent_one = new global::Gtk.Entry();
		this.sub_ent_one.CanFocus = true;
		this.sub_ent_one.Name = "sub_ent_one";
		this.sub_ent_one.IsEditable = true;
		this.sub_ent_one.InvisibleChar = '●';
		this.hbox5.Add(this.sub_ent_one);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.sub_ent_one]));
		w6.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("-");
		this.hbox5.Add(this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.sub_ent_two = new global::Gtk.Entry();
		this.sub_ent_two.CanFocus = true;
		this.sub_ent_two.Name = "sub_ent_two";
		this.sub_ent_two.IsEditable = true;
		this.sub_ent_two.InvisibleChar = '●';
		this.hbox5.Add(this.sub_ent_two);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.sub_ent_two]));
		w8.Position = 2;
		// Container child hbox5.Gtk.Box+BoxChild
		this.subtract = new global::Gtk.Button();
		this.subtract.CanFocus = true;
		this.subtract.Name = "subtract";
		this.subtract.UseUnderline = true;
		this.subtract.Label = global::Mono.Unix.Catalog.GetString("subtract");
		this.hbox5.Add(this.subtract);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.subtract]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.mult_ent_one = new global::Gtk.Entry();
		this.mult_ent_one.CanFocus = true;
		this.mult_ent_one.Name = "mult_ent_one";
		this.mult_ent_one.IsEditable = true;
		this.mult_ent_one.InvisibleChar = '●';
		this.hbox2.Add(this.mult_ent_one);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.mult_ent_one]));
		w11.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("x");
		this.hbox2.Add(this.label3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label3]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.mult_ent_two = new global::Gtk.Entry();
		this.mult_ent_two.CanFocus = true;
		this.mult_ent_two.Name = "mult_ent_two";
		this.mult_ent_two.IsEditable = true;
		this.mult_ent_two.InvisibleChar = '●';
		this.hbox2.Add(this.mult_ent_two);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.mult_ent_two]));
		w13.Position = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.multiply = new global::Gtk.Button();
		this.multiply.CanFocus = true;
		this.multiply.Name = "multiply";
		this.multiply.UseUnderline = true;
		this.multiply.Label = global::Mono.Unix.Catalog.GetString("multiply");
		this.hbox2.Add(this.multiply);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.multiply]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.div_ent_one = new global::Gtk.Entry();
		this.div_ent_one.CanFocus = true;
		this.div_ent_one.Name = "div_ent_one";
		this.div_ent_one.IsEditable = true;
		this.div_ent_one.InvisibleChar = '●';
		this.hbox3.Add(this.div_ent_one);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.div_ent_one]));
		w16.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("/");
		this.hbox3.Add(this.label5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label5]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.div_ent_two = new global::Gtk.Entry();
		this.div_ent_two.CanFocus = true;
		this.div_ent_two.Name = "div_ent_two";
		this.div_ent_two.IsEditable = true;
		this.div_ent_two.InvisibleChar = '●';
		this.hbox3.Add(this.div_ent_two);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.div_ent_two]));
		w18.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.divide = new global::Gtk.Button();
		this.divide.CanFocus = true;
		this.divide.Name = "divide";
		this.divide.UseUnderline = true;
		this.divide.Label = global::Mono.Unix.Catalog.GetString("divide");
		this.hbox3.Add(this.divide);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.divide]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 416;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.add.Clicked += new global::System.EventHandler(this.OnAddClicked);
		this.subtract.Clicked += new global::System.EventHandler(this.OnSubtractClicked);
		this.multiply.Clicked += new global::System.EventHandler(this.OnMultiplyClicked);
		this.divide.Clicked += new global::System.EventHandler(this.OnDivideClicked);
	}
}
