//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCViewsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int Id { get; set; }
        public string Summary { get; set; }
        public int Rating { get; set; }
        public string Body { get; set; }
        public string Reviewer { get; set; }
    }
}
