iNSERT into reviews values (1,'GREAT',10,'Great movie','R.K')
iNSERT into reviews values (2,'Good',9, 'good movie','R.K')
iNSERT into reviews values (3,'Alright',8,'alright movie','R.K')
iNSERT into reviews values (4,'Worth Watching',7,'worth watching movie','R.K')
iNSERT into reviews values (5,'Meh, could have been better',6,'meh movie','R.K')
iNSERT into reviews values (6,'boring',5,'boring movie','R.K')
iNSERT into reviews values (7,'kinda wack',4,'wack movie','R.K')
iNSERT into reviews values (8,'Super Lame',3,'lame movie','R.K')
iNSERT into reviews values (9,'Dont waste your time',2,'waste movie','R.K')
iNSERT into reviews values (10,'I want my money back',1,'money back movie','R.K')
iNSERT into reviews values (11,'Hell Nah',0,'hell nah movie','R.K')